--- 
 - name : update packages 
   apt : upgrade=dist

 - name : create slurm directories
   file: path={{ item }} state=directory owner=slurm group=slurm mode=0744 recurse=yes
   with_items:
    - /var/slurm/run
    - /var/slurm/spool

 - name : install package - {{ item }}
   apt : name={{ item }} state=present
   with_items:
    - ntp
    - munge
    - bsd-mailx
    - slurm-llnl

 - name : copy hosts file
   copy : src=hosts dest=/etc/hosts

 - name : add localhost
   shell : echo 127.0.1.1 {{ inventory_hostname }} >> /etc/hosts

 - name : set hostname
   shell : echo {{ inventory_hostname }} > /etc/hostname && hostname -F /etc/hostname

 - name : copy munge key
   copy : src=munge.key dest=/etc/munge/munge.key owner=munge group=munge mode=0400

 - name : copy slurm configuration
   copy : src=slurm.conf dest=/etc/slurm-llnl/slurm.conf owner=slurm group=slurm mode=0444

 - name : copy cgroup files
   copy : src={{ item }} dest=/etc/slurm-llnl/{{ item }} owner=slurm group=slurm mode=0444
   with_items:
    - cgroup_allowed_devices_file.conf
    - cgroup.conf

 - name : restart services
   service : name={{ item }} state=started enabled=yes
   with_items:
     - ntp
     - munge

 - name : start controller
   service : name=slurm-llnl state=started enabled=yes

# - name : start nodes 
#   service : name=slurmd state=started enabled=yes
#   when : "'slurm_nodes' in group_names"
